# site settings

## blog pages

baseurl: 

title: "Embedded Freak"
email: "lukmaan.me@gmail.com"
description: >-
    Howto's on device drivers, embedded system, raspberry pi,
    linux.
url: "http://lukzy.xyz"
github_username: nabstar
markdown: kramdown
permalink: pretty
